bamFolder: "sc_bams/"
bamSuffix: ".bam"
out_folder: "MBV_Morris/"
dataCode: "ftd_sc_meta"
#VCF: "/sc/arion/projects/ad-omics/GSA_genotypes/gsa_may2021/michael_QC_data/ALL_samples/all_ancestry_microglia_samples_post_imputation/Genotype_QC_Pipeline_2.0/output/clean_data/gsa_microglia_05-2021_allAncestry_MAF.vcf.gz"
#VCF: "/sc/arion/projects/bigbrain/data/NYGC_Flagship/Jin_WGS_pipeline2/export/NYGC_Flagship.maf0.01.vcf.gz"
#VCF: "/sc/arion/projects/bigbrain/data/NYGC_Flagship/fastq_from_NYGC/ALS_Consortium_VCF/CGND_4857DNASamples_AN3929_GRM_WGS/joint_vcf/CGND_4857DNASamples_AN3929_GRM_WGS_2023-08-23_chr1.recalibrated_variants.vcf.gz"
VCF: "/sc/arion/projects/als-omics/raw_data/ForJack/DEM_EUR.renamed.vcf.gz"
