bamFolder: "test_inputs/"
bamSuffix: ".bam"
out_folder: "output/"
dataCode: "gsa_microglia_05-2021_allAncestry"
VCF: "/sc/arion/projects/ad-omics/GSA_genotypes/gsa_may2021/michael_QC_data/ALL_samples/all_ancestry_microglia_samples_post_imputation/Genotype_QC_Pipeline_2.0/output/clean_data/gsa_microglia_05-2021_allAncestry_MAF.vcf.gz"
